language: node_js

node_js:
  - 10
  - 12
  - lts/*

os:
  - linux
  - osx
  - windows

deploy:
  provider: npm
  email: tanxuan_2013@163.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master

cache: npm

install:
  - npm install

git:
  quiet: true
  depth: 1

script:
  - npm run build
  - npm run doc
  - npm run coverage