language: node_js

node_js:
  - 10
  - 12
  - lts/*

os:
  - linux
  - osx
  - windows

cache: npm

install:
  - npm install

git:
  quiet: true
  depth: 1

script:
  - npm run build
  - npm run doc

after_success: npm run coverage