language: node_js

node_js:
  - 10
  - 12
  - lts/*

os:
  - linux
  - osx
  - windows

cache: npm

install:
  - npm install

# git:
#   quiet: true
#   depth: 1

stages:
  - test
  - doc
  - coverage
  - name: deploy

jobs:
  include: 
    - stage: test
    script:
      - node --version
      - npm --version
      - echo "Testing Start ..."
      - npm run test
      - echo "Testing End..."

    - stage: doc
    script:
      - echo "JsDoc Start ..."
      - npm run doc
      - echo "JsDoc End..."

    - stage: coverage
    script:
      - echo "Coverage Start..."
      - npm run coverage
      - echo "Coverage End..."

    - stage: deploy
    script:
      - echo "Build Start..."
      - npm --version
      - npm run build
      - echo "Build End..."

    deploy:
      provider: npm
      email: tanxuan_2013@163.com
      api_key: "$NPM_TOKEN"
      skip_cleanup: true
      keep-history: true
      local-dir: lib
      on:
        branch: master